/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unique.Consultas;

import Tabelas.Mensalidade;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.HibernateUtil;

/**
 *
 * @author CarlosEduardo
 */
public class Observacoes extends javax.swing.JFrame {

    /**
     * Creates new form Obeservacoes
     */
    
    Session conexao;
    Transaction tx;
    Mensalidade mensalidade;
    int caracteresRestantes = 255;
    
    public Observacoes() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
        lblCaracteres.setText(caracteresRestantes + " caracteres restantes.");
    }
    
    public void BuscarObs(Mensalidade m){
        mensalidade = m;
        
        if(m.getObservacao() != null){
            memoObs.setText(m.getObservacao());
            caracteresRestantes = 255 - memoObs.getText().length();
            lblCaracteres.setText(caracteresRestantes + " caracteres restantes.");
        } else{
            memoObs.setText("");
        }
        
        memoObs.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        memoObs = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCaracteres = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Observações de Mensalidade");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Observações");

        memoObs.setColumns(20);
        memoObs.setLineWrap(true);
        memoObs.setRows(5);
        memoObs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memoObsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                memoObsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                memoObsKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(memoObs);

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unique/Imagens/dialog-ok.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unique/Imagens/list-remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCaracteres.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCaracteres.setText("255 caracteres restantes.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(197, 225, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCaracteres, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCaracteres)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        conexao = HibernateUtil.openSession();
        tx = conexao.beginTransaction();
        
        mensalidade.setObservacao(memoObs.getText());
        
        boolean funcionou = true;
        
        try{
            conexao.saveOrUpdate(mensalidade);
            tx.commit();
        } catch(Exception e){
            funcionou = false;
            JOptionPane.showMessageDialog(this, "Erro ao salvar observação. Motivo: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        conexao.close();
        
        if(funcionou){
            JOptionPane.showMessageDialog(this, "Observação salva com sucesso. Pressione OK para Sair", "Erro", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void memoObsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memoObsKeyReleased
        // TODO add your handling code here: 
        
        if(memoObs.getText().length() > 255){
            memoObs.setText(memoObs.getText().substring(0, 255));
        } else{
            caracteresRestantes = 255 - memoObs.getText().length();
            lblCaracteres.setText(caracteresRestantes + " caracteres restantes.");
        }    
    }//GEN-LAST:event_memoObsKeyReleased

    private void memoObsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memoObsKeyTyped
        // TODO add your handling code here:
//        if(memoObs.getText().length() > 255){
//            JOptionPane.showMessageDialog(this, "O campo de observação permite no máximo 255 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
//            memoObs.setText(memoObs.getText().substring(0, 255));
//        } else{
//            caracteresRestantes = 255 - memoObs.getText().length();
//            lblCaracteres.setText(caracteresRestantes + " caracteres restantes.");
//        }
    }//GEN-LAST:event_memoObsKeyTyped

    private void memoObsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memoObsKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_memoObsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Observacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Observacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Observacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Observacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Observacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCaracteres;
    private javax.swing.JTextArea memoObs;
    // End of variables declaration//GEN-END:variables
}
